apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: fpfordel
  namespace: NAMESPACE_VAL
  labels:
    team: teamforeldrepenger
spec:
  env:
  - name: APP_NAME
    value: fpfordel
  - name: APP_VERSION
    value: RELEASE_VERSION
  - name: APP_TEAM
    value: teamforeldrepenger
  image: repo.adeo.no:5443/fpfordel:RELEASE_VERSION
  port: 8080
  team: teamforeldrepenger
  ingresses:
  - "INGRESS_URL"
  preStopHookPath: /fpfordel/internal/health/preStop
  #prometheus:
    #enabled: true
    #path: /fpfordel/internal/prometheus
  istio: # Optional.
    enabled: false # Optional. When true, envoy-proxy sidecar will be injected into pod and https urls envvars will be rewritten
  logformat: accesslog # Optional. The format of the logs from the container if the logs should be handled differently than plain text or json
  logtransform: dns_loglevel # Optional. The transformation of the logs, if they should be handled differently than plain text or json
  webproxy: false # Optional. Expose web proxy configuration to the application using the HTTP_PROXY, HTTPS_PROXY and NO_PROXY environment variables.
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/dev/srvfpfordel
        mountPath: /secrets/serviceuser
      - kvPath: oracle/data/dev/creds/fpfordel_t4-user
        mountPath: /secrets/credentials
  sidecar: true # refresh token
  liveness:
    path: /fpfordel/internal/health/isAlive
    port: 8080
    initialDelay: 30
    periodSeconds: 10
    failureThreshold: 10
    timeout: 1
  readiness:
    path: /fpfordel/internal/health/isReady
    port: 8080
    initialDelay: 30
    timeout: 1
  replicas:
    min: 3
    max: 3
    cpuThresholdPercentage: 80
  resources:
    limits:
      cpu: 500m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 1024Mi
