name: Build, push, and deploy

on:
  push:
    branches:
      - master 
env:
  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
  ORACLE_INIT: initdb.sql
  ORACLE_ARGS:  -d -p 1521:1521 --name oracle-xe -e ORACLE_DISABLE_ASYNCH_IO=true
  ORACLE_IMAGE: wnameless/oracle-xe-11g-r2
  ORACLE_SID: XE
  ORACLE_HOME: /u01/app/oracle/product/11.2.0/xe
  CLUSTER: dev-fss
  NAMESPACE: t4
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_BASE: docker.pkg.github.com/${{ github.repository }}/fpfordel
         
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     
      - name: Sjekk ut kode
        uses: actions/checkout@v2
    
      - name: Cache maven repository
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
     
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
          
      - name: Hent tag    
        run: echo "::set-env name=TAG::$(git log -1 --pretty='%ad' --date=format:'%Y%m%d%H%M%S')-$(echo $GITHUB_SHA | cut -c1-7)"  
           
      - name: Hent og start Oracle image
        id: oracle
        shell: bash
        run: |
          echo "Henter og starter Oracle image $ORACLE_IMAGE"
          echo "##[set-output name=pod;]$(docker run $ORACLE_ARGS $ORACLE_IMAGE)"     
    
      - name: Vent 60 sekunder på Oracle oppstart
        shell: bash
        run: |
          echo "Venter på oppstart av Oracle pod ${{ steps.oracle.outputs.pod }}"
          sleep 60 
          docker cp $ORACLE_INIT ${{ steps.oracle.outputs.pod }}:/$ORACLE_INIT
          docker exec -e ORACLE_SID=$ORACLE_SID -e PATH=$PATH:$ORACLE_HOME/bin -e ORACLE_HOME=$ORACLE_HOME ${{ steps.oracle.outputs.pod }} sqlplus system/oracle @$ORACLE_INIT
   
      - name: Kompiler
        run: |
          echo "::set-env name=IMAGE::$IMAGE_BASE:$TAG" 
          mvn --quiet clean install --batch-mode --settings .github/workflows/.m2/settings.xml -Dchangelist= -Dsha1=-$TAG -Dsonar.projectKey="navikt_fpfordel" -Dsonar.login=${SONAR}
        env:
          SONAR: ${{ secrets.SONAR }} 
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.GHA }}  
     
      - name: Bygg, tag og push Docker image  
        run: |
          docker build --tag $IMAGE --tag $IMAGE_BASE:latest .
          echo  $GITHUB_TOKEN | docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} --password-stdin
          docker push $IMAGE_BASE   
    
      - name: Deploy til cluster/namespace
        uses: nais/deploy/actions/deploy@v1 
        env:
          RESOURCE: naiserator.yaml
          PRINT_PAYLOAD: true
          VARS: ${{ env.CLUSTER }}-${{ env.NAMESPACE }}.json
          
      - name: Informer om deployment
        if: success()
        run: |
         echo "Informerer om deployment av $TAG"
             curl -X POST \
            --url  https://api.github.com/repos/${{ github.repository }}/issues \
            --header "authorization: Bearer $GITHUB_TOKEN" \
            --header "content-type: application/json" \
            --data '{
              "labels": ["deployment","dev-fss","t4"],
              "title": "Deployment av ${{env.TAG}} til ${{env.CLUSTER}}-${{env.NAMESPACE}} var OK",
              "body":  "Kommenter med <b>/promote ${{env.TAG}} env namespace</b>, hvor <b>env</b> er et gyldig clusternavn og <b>namespace</b> et eksisterende namespace i det clusteret. Kommenter med <b>/prod</b> for å deploye trunk fra master til prod"
            }'     
