name: Build, push, and deploy

on:
  push:
    branches:
      - gha 
env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/fpfordel:${{ github.sha }}
  GITHUB_USERNAME: x-access-token
  GITHUB_PASSWORD: ${{ secrets.GPR }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Hent oracle image
        shell: bash
        run: |
          echo "Starter Oracle image"
          docker run -d -p 1521:1521 --name oracle-xe -e ORACLE_DISABLE_ASYNCH_IO=true wnameless/oracle-xe-11g-r2
      - name: Vent 60 sekunder på Oracle oppstart
        shell: bash
        run: |
          echo "Venter på oppstart av Oracle"
          docker ps
          sleep 60 
          docker cp initdb.sql `docker ps | tail -1 | awk  '{ print $1}'`:/initdb.sql
          docker exec -e ORACLE_SID=XE -e PATH=$PATH:$ORACLE_HOME/bin -e ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe `docker ps | tail -1 | awk  '{ print $1}'` /u01/app/oracle/product/11.2.0/xe/bin/sqlplus system/oracle @initdb.sql
      - name: Compile
        run: |
          echo "$Bygger artifakt $(echo $GITHUB_SHA | cut -c1-7)"
          mvn --quiet clean deploy --batch-mode --settings .github/workflows/.m2/settings.xml 
          echo "Bygget artifakt"
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.GIHUB_ACCESS_TOKEN }}  
      - name: Sette Docker navn og tag
        run: |
          echo $IMAGE > .docker_image
          echo "$(git log -1 --pretty='%ad' --date=format:'%Y%m%d%H%M%S')-$(echo $GITHUB_SHA | cut -c1-7)" > .docker_tag
      - name: Bygge Docker image
        run: docker build . --pull -t $IMAGE:$(cat .docker_tag)