name: Deploy
on: repository_dispatch

jobs:
  deploy:
    name: Deploy to environment
    runs-on: ubuntu-latest
    container: navikt/deployment-cli:0.4.0
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Deploy til dev-fss t4
        uses: nais/deploy/actions/deploy@v1 
        env:
          DRY_RUN: false
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: naiserator.yml
          PRINT_PAYLOAD: true
          VARS: dev-fss-t4.json
