name: Promote
on:
  repository_dispatch:
    types: [promote-command]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_BASE: docker.pkg.github.com/${{ github.repository }}/fpfordel
      
jobs:
  promote:
    runs-on: ubuntu-latest
    
    steps:
       
      - name: Set variabler for image, namespace og cluster
        run: |
           echo "::set-env name=TAG::$(echo ${{ github.event.client_payload.slash_command.arg1 }} | cut -c1-7)"  
           echo "::set-env name=IMAGE::$IMAGE_BASE:${{ github.event.client_payload.slash_command.arg1 }}" 
           echo "::set-env name=CLUSTER::${{ github.event.client_payload.slash_command.arg2 }}"         
           echo "::set-env name=NAMESPACE::${{ github.event.client_payload.slash_command.arg3 }}"         
       
      - name: Sjekk ut kode
        uses: actions/checkout@v1
    
      - name: Promoter til cluster og namespace
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ env.CLUSTER }}
          RESOURCE: naiserator.yaml
          PRINT_PAYLOAD: true
          VARS: ${{ env.CLUSTER }}-${{ env.NAMESPACE }}.json 
          
      - name: Oppdater kommentar med deployment status ved feil
        if: failure()
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GHA }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            >promote ${{ env.IMAGE }} til ${{ env.CLUSTER }}-${{ env.NAMESPACE }} feilet
          reaction-type: -1          
 
      - name: Oppdater kommentar med deployment status
        if: success()
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GHA }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            >promote ${{ env.IMAGE }} til ${{ env.CLUSTER }}-${{ env.NAMESPACE }} var OK 
          reaction-type: rocket
                  
