on:
  issues: {types: opened}
env:
  ORACLE_INIT: initdb
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.3.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue = { owner: context.issue.owner, repo: context.issue.repo, issue_number: context.issue.number }
            github.issues.createComment({...issue, body: '${{env.ORACLE_INIT}} Thanks for reporting!'})


